name: Publish README with Last Project

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: # manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run update script
        run: node .github/scripts/update-readme-v2.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY_7X9K2M }}
          USERNAME: sagawrr

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md recent-projects.svg
          git commit -m "🔮 MATRIX UPDATE: Neural network synchronized with latest project data" || echo "No changes to commit"
          git push
